### ISSUE TITLE
> v1.25.0 Fog::Formatador#table is broken and Fog::Collection is acting differently

### ISSUE THREAD

**Issue by cphrmky** [fog/fog-core#124]
@plribeiro3000 here's the issue I ran into that caused the back-and-forth in fog/fog-softlayer@454cfd21.

##### A picture being worth 1,000 words, let's do it like this:
Here's a short screencast where you can see what I ran into that made me track it down this far.
http://screencast.com/t/jZOY4K5l

I tracked it down a little bit on the table method as below pictures show.  Specifically look at the difference in output of the call to `Formatador.ancestors` at the bottom of both.
Here's 1.25.0  http://cl.ly/image/3v3s2v0k1t3j (`#table` not broken)
Here's 1.27.3 http://cl.ly/image/0U1j2o3O3J1w (`#table` is broken)

Let me know if I can help.

/cc @geemus @tokengeek @michaeljb @fernandes

**Comment by geemus** [comment]
That should fix the table stuff ^. I'm less sure (off hand) of the collection issue.

**Comment by geemus** [comment]
@starbelly could you take a look and see if you have ideas? Basically instead of showing the inspect of the models in the collection it is just showing the object id (but not it's attributes). The screencast might make it clearer than I feel like I am. Thanks!

**Comment by plribeiro3000** [comment]
@cphrmky Thanks!

@geemus Good catch. I think the error might be related to [#nested_objects_string](https://github.com/fog/fog-core/blob/master/lib/fog/formatador.rb#L63)

**Comment by cphrmky** [comment]
@starbelly,

Possibly worth noting, that when I build with @geemus's patch from a11a15f the Fog::Collection issue is gone?  http://screencast.com/t/Q5i21CYwMM [< 60s]

**Comment by starbelly** [comment]
I need to do an audit for Formatador calls, I'll get on that. @cphrmky when you do `sl.flavors` with https://github.com/fog/fog-core/commit/a11a15f43e830b2f3fbd20adc6cafa301469b601 applied are you still just seeing the the object ids? I imagine it's still just showing object ids, just want to confirm.

**Comment by cphrmky** [comment]
@starbelly no, that's what I was getting at.  The screencast in my above comment is showing the proper inspection-style objects as members of the collection with a11a15f (and no other changes) applied.

**Comment by cphrmky** [comment]
@starbelly just realized the screencast could've been more clear.  In the second half of it, when I checkout "master" in the fog-core repo then run through it again, that's fog/fog-core@a11a15f, the current HEAD of this repo.

**Comment by starbelly** [comment]
It's clear, I just didn't slow down enough to check out that link. Beautiful!

**Comment by starbelly** [comment]
P.S. Bug reports via screencast for issues like these is simply awesome :+1:

**Comment by cphrmky** [comment]
> Beautiful!

That it's working, agreed.

I'm still wondering why the heck that was happening though.  root-cause style.  Superficially, I guess it's fixed-enough-for-open-source and we can all have :beers:, I'd love to see any further theories you might have on it though.

**Comment by starbelly** [comment]
It's because there's calls in the source to Formatador that are being picked up by Fog::Formatador and Fog::Formatador didn't have display_table and so forth implemented. @geemus added those and more importantly prefixed the calls to Formatador with `::` to instruct Ruby to look from the top down for Formatador. I really don't like that about Ruby. It should be able to decipher on it's own that you mean Formatador not Fog::Formatador. I've only ever seen this behavior in Ruby.

**Comment by cphrmky** [comment]
Ah, I didn't catch that subtlety in @geemus's fix, appreciate the explanation.   

Sounds like we're good to close this out.  I'll be sure to unlock knife-softlayer from overriding with fog-core 1.25.0 once the next release of fog-core is cut.

Thx to all.
