### ISSUE TITLE
Fog CLI output no longer showing actual data

### ISSUE THREAD

**Issue by eherot** [fog/fog-core#126]
I'm not sure how to describe this in technical terms, but somewhere between fog-core 1.27.2 and 1.27.3, output in the command line tool (and Pry and IRB) that used to look like this:

```
>> Fog::Compute::AWS.new.servers
  <Fog::Compute::AWS::Servers
    filters={}
    [
      <Fog::Compute::AWS::Server
        id="i-01234567",
        ami_launch_index=0,
        associate_public_ip=nil,
        availability_zone="us-east-1d",
...etc..
```
Started looking like this instead:
```
>> Fog::Compute::AWS.new.servers
  <Fog::Compute::AWS::Servers
  >
>> 
```
As far as I can tell nothing else about the functionality of the library seems to be affected.

**Comment by cphrmky** [comment]
@eherot is this still happening if you build with the latest `HEAD` of fog-core?  I believe that this issue has been addressed.

**Comment by eherot** [comment]
Ah, yes. It does seem to have been addressed in `HEAD`.

**Comment by geemus** [comment]
Yeah, apologies for the issue. Will probably follow up with a new release
in the relatively near term.
