### ISSUE TITLE
Billing

### ISSUE THREAD

**Issue by fernandes** [fog/fog-core#127]
Hey guys,

I've seen fog-core has a [Billing Module](https://github.com/fog/fog-core/blob/7b9df376929ec1f4344047e32745f279f63b6bac/lib/fog/billing.rb) but none of the providers have support for billing stuff yet. Do you have any example how to implement?

I'm adding support on fog softlayer, but API is a little bit complex to add support like Compute or DNS, my ideia is add support for Account stuff under Account module and Billing stuff under Billing module trying to keep Fog standards.

Suggestions?

// cc @cphrmky

**Comment by plribeiro3000** [comment]
Hey @fernandes. Right now just `stormondemand` use this Service. I think the best option would be to have a structure like the one we have for `Compute` as you already pointed out.

My only concern here is that as we started moving stuff out of `Fog` we discovered that this Service and another ones are being used by just one Provider (`StomOnDemand where the rule is to have at least 3 Providers that can implement a new Service to actually push it to `Fog::Core`.

@geemus What are your thoughts on this one?

**Comment by fernandes** [comment]
hey @plribeiro3000 thank you for response

I saw `storm on demand` implementation, its very simple, has only two collections/models, as (I already supposed) I'm gonna be the first one... I'll try to follow the more generic possible structure so we can share with other modules.

Lets check if @geemus or @cphrmky have another consideration

**Comment by geemus** [comment]
Yeah. Trying to keep it generic would be good, though it can be hard to really do so without a few examples to draw from. Otherwise, certainly not opposed. Thanks!
