### ISSUE TITLE
Formatador breaks with single objects with `#map` defined.

### ISSUE THREAD

**Issue by tokengeek** [fog/fog-core#138]
Brightbox's `CloudIp` object can no longer be inspected because `#map`
is already defined to "port" them between servers.

```
>> service.cloud_ips
ArgumentError: wrong number of arguments (0 for 1)
        from /home/paul/.gem/ruby/2.2.1/gems/fog-brightbox-0.7.1/lib/fog/brightbox/models/compute/cloud_ip.rb:32:in `map'
        from /home/paul/.gem/ruby/2.2.1/gems/fog-core-1.29.0/lib/fog/formatador.rb:87:in `inspect_object'
        from /home/paul/.gem/ruby/2.2.1/gems/fog-core-1.29.0/lib/fog/formatador.rb:74:in `block in nested_objects_string'
        from /home/paul/.gem/ruby/2.2.1/gems/formatador-0.2.5/lib/formatador.rb:92:in `indent'
        from /home/paul/.gem/ruby/2.2.1/gems/fog-core-1.29.0/lib/fog/formatador.rb:43:in `indent'
        from /home/paul/.gem/ruby/2.2.1/gems/fog-core-1.29.0/lib/fog/formatador.rb:74:in `nested_objects_string'
        from /home/paul/.gem/ruby/2.2.1/gems/fog-core-1.29.0/lib/fog/formatador.rb:56:in `object_string'
        from /home/paul/.gem/ruby/2.2.1/gems/fog-core-1.29.0/lib/fog/formatador.rb:14:in `block in format'
        from /home/paul/.gem/ruby/2.2.1/gems/formatador-0.2.5/lib/formatador.rb:92:in `indent'
        from /home/paul/.gem/ruby/2.2.1/gems/fog-core-1.29.0/lib/fog/formatador.rb:43:in `indent'
        from /home/paul/.gem/ruby/2.2.1/gems/fog-core-1.29.0/lib/fog/formatador.rb:14:in `format'
        from /home/paul/.gem/ruby/2.2.1/gems/fog-core-1.29.0/lib/fog/core/model.rb:24:in `inspect'
        from /home/paul/.gem/ruby/2.2.1/gems/fog-core-1.29.0/lib/fog/formatador.rb:87:in `block in inspect_object'
        from /home/paul/.gem/ruby/2.2.1/gems/fog-core-1.29.0/lib/fog/core/collection.rb:19:in `map'

```

It seems when the code that is now `Fog::Formatador` was extracted from
`CollectionString` it became more general rather than just for collections.

So when trying to enumerate the collection of Cloud IPs, because `map` is assumed rather than `each` (which appears to be an implementation detail here https://github.com/fog/fog-core/blob/master/lib/fog/formatador.rb#L87) an error occurs due to the arity difference.

I plan to deprecate `map` in `fog-brightbox` however this is still a bug in Formatador.

* We should be using `each` to confirm if an Object is `Enumerable`

I'll try to fix it Monday unless anyone else wants to try.

Original report: fog/fog-brightbox#17

**Comment by geemus** [comment]
Sounds reasonable, thanks for the detailed report. Just let me know if there is anything I can help with. Thanks!

**Comment by robd** [comment]
I wonder if it would be better to explicitly check for an Enumerable object here. That way calling `map` on the object should be fine because it should expose the Enumerable API. 

Just checking for `each` would cause a problem for an object which defined `each`, but didn't have a `map` method. (`NoMethodError` would be thrown, I guess.)

**Comment by cphrmky** [comment]
Agreed

```ruby
object.is_a?(Enumerable)
```

would be better still than `.responds_to(:each)`

**Comment by tokengeek** [comment]
Yeah. I agree that for this case we should check for `Enumerable`

I need to clean the tests up because there's several versions of the check which looks messy.

**Comment by tokengeek** [comment]
Just cleaning up the test cases and an immediate curiosity stands out. Checked the `Fog::Collection` class and oddly, collections have their own attributes?

https://github.com/fog/fog-core/blob/master/lib/fog/core/collection.rb#L6-L8

I'll leave it in place but unless someone can point to a case where this is used I think this behaviour is a bit confusing.

I've switched to using the `Enumerable` check and that fixes the above case.

Looking at it though we need more cases because `Fog::Formatador` is used to inspect everything now and it's not particularly robust.

**Comment by geemus** [comment]
I think the collection attributes are expected, it doesn't get used a ton, but I think we use it at least in the storage container case (where there are often pagination or filter related attributes, or at least that is how we have implemented them). I guess they could be done as either non-attribute instance variables and/or we could NOT include this in general and only include it on those few cases where it might need to be.

**Comment by tokengeek** [comment]
Yeah. Just confused me since the original specs were just passing in the same object for collections, nested things etc.

Can wait for now.
