### ISSUE TITLE
Ruby warnings Comparable & Return nil

### ISSUE THREAD

**Issue by mattheworiordan** [fog/fog-core#142]
I receive the following warnings when require Fog with Ruby 2.2.1:

```
vendor/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/fog-core-1.29.0/lib/fog/core/service.rb:166: warning: Comparable#== will no more rescue exceptions of #<=> in the next release.
vendor/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/fog-core-1.29.0/lib/fog/core/service.rb:166: warning: Return nil in #<=> if the comparison is inappropriate or avoid such comparison.
```

I am on Fog master, commit f16fae7b0b40af3212facbf317a76628e353fcc5

**Comment by mattheworiordan** [comment]
Note I was using `fog` latest commit, but not explicitly pulling in the latest commit on master with `fog-core`.  After including `gem 'fog-core';, git: 'https://github.com/fog/fog-core.git'` this warning no longer appears.

**Comment by plribeiro3000** [comment]
Awesome. Thanks for the update!

**Comment by fcheung** [comment]
FYI this was #134

**Comment by geemus** [comment]
Thanks for updating, nice to know we got it fixed already.
