### ISSUE TITLE
`==` in Fog::Model currently compares actual objects; should it instead compare `identity`?

### ISSUE THREAD

**Issue by ihmccreery** [fog/fog-core#148]
I'm working on implementing more rigorous tests for `fog-google`, and I was surprised to see that `==` isn't reimplemented in `Fog::Model` to compare `identity` or something similar.  In particular, I would expect that:

```
> instance = Fog::Compute[:provider].servers.create(params)
...
> Fog::Compute[:provider].servers.all.include? instance
```

would return `true`, but because `==` is still comparing literal Ruby objects, it returns false.

**Comment by geemus** [comment]
Ah, interesting. I guess it just hasn't come up? Maybe identity makes more sense, what use case were you thinking about?

**Comment by ihmccreery** [comment]
Honestly, I'm just trying to beef up the tests.  I didn't have a particular use case past that, but any time we have two references to the same resource, this would come up, right?

I'll take a crack at the definition and submit a pull request.

**Comment by geemus** [comment]
Yeah, I suppose so. I think in many cases the usage tends to be more around using reloads, for better or worse (ie you update the reference you already have, rather than ending up with distinct references).

**Comment by ihmccreery** [comment]
More specifically, what I'd like to do is:

```
assert_includes collection.all, instance
```

but what I currently have to do is:

```
assert_includes collection.all.map(&:identity), instance.identity
```

**Comment by geemus** [comment]
Makes sense. Closing in favor of continuing discussion on the PR.
