### ISSUE TITLE
issue with ssh command: interactive input.

### ISSUE THREAD

**Issue by allomov** [fog/fog-core#151]
Hey, all.

I have an issue with ssh to my server with fog. I can ssh in terminal using password, but when I try to do it in script I get invitation to enter a password interactively (`ubuntu@x.x.x.x's password:`):
```ruby
server.username = "ubuntu"
server.password = "password"
server.ssh("pwd")
ubuntu@x.x.x.x's password:
=> [#<Fog::SSH::Result:0x007ff9bc943d98 @command="pwd", @status=0, @stderr="", @stdout="/home/ubuntu\r\n">]
```
Everything works after I enter password manually. I also got this text before:
```
Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text.
```
I tried to run it both with `highline` and `ruby-termios`, but it didn't help. 

Some lines about my environment:
```
ruby 2.1.5p273
fog-core (1.30.0, 1.29.0)
ruby-termios (0.9.6)
net-ssh (2.9.2, 2.9.1)
```

Could you tell how can I run ssh commands without entering password?

Thank you,
Alex L.

**Comment by allomov** [comment]
I see now that a problem is in the way I set ssh password to a server model: when I set it with attr accessor it doesn't work correctly. When I pass a password as a `ssh` method parameter, then it works.

The right way to call ssh for me now is 
```ruby
server.ssh('pwd', password: 'pass')
```

Is it correct behavior?

**Comment by geemus** [comment]
@allomov yeah, I think that should be right. I believe it is set that way (instead of attr_accessor) to be more cautious about keeping the password around and/or displaying it. Glad to hear you found what you needed.

**Comment by allomov** [comment]
@geemus I have the same issue with `scp` method now. But passing password into options doesn't fix it.

Could you tell how I can fix it ?

**Comment by allomov** [comment]
As far as I can see `ssh_options` is hidden from caller in `scp` method [[link to source](https://github.com/fog/fog-core/blob/aad1cce35669956284010235b5a3163d172ca421/lib/fog/compute/models/server.rb#L71)].

**Comment by geemus** [comment]
I think there is an accessor for ssh_options also, so I think you can set values in there and have them pass through (though I agree in is a bit weird/inconsistent with ssh).

**Comment by cphrmky** [comment]
If all else fails and you're stuck you can do this:

```ruby
Fog::SCP.new(ssh_ip_address, username, :password => ssh_password).upload(local_file, remote_path)
```

**Comment by allomov** [comment]
@cphrmky thank you, I've just used this solution and it worked. Amazing, how fast you are.

**Comment by allomov** [comment]
@geemus I can make PR to accept password option in `scp` method. what do you think about it ?

**Comment by geemus** [comment]
Sounds great. We'll have to be careful about making it backwards compatible, but sounds super.

**Comment by cphrmky** [comment]
> Amazing, how fast you are.

@allomov don't tell anyone, they'll want me to get more things done...
