### ISSUE TITLE
Net-ssh upgraded and breaking fog-core deps on Ruby < 2.0 compliant stacks.

### ISSUE THREAD

**Issue by Temikus** [fog/fog-core#162]
I noticed fog-google builds started failing as I have just made a no-op change before release:
https://travis-ci.org/fog/fog-google

Builds failing on fog-core on:
Ruby - 1.8.7
Ruby - 1.9.2
Ruby - 1.9.3
ree
jruby

Looking at the dep graph, it's fog-core's dependency net-ssh, which just updated a couple of hours ago:
https://rubygems.org/gems/net-ssh/
3.0.1 - September 25, 2015 (177 KB)

I created a https://github.com/fog/fog-core/pull/161 to try and kick off the travis build and check if locking the version works adequately.

However, please, note that I'm not that familiar with core code, so please, check this first.

/CC @geemus @plribeiro3000

**Comment by plribeiro3000** [comment]
I'm on it. Just waiting for the build result. Thank you for spotting that!

**Comment by plribeiro3000** [comment]
and btw, `fog-google` should drop support to ruby `1.8.7`, `1.9.2`, `ree` and `jruby-18mode` since fog `2.0.0` does not support it anymore.

**Comment by Temikus** [comment]
@plribeiro3000 I noticed that fog-core still has 1.9.2 rubies in CI config.
Should I propose a change there as well?

**Comment by plribeiro3000** [comment]
Yes. We need to update `fog-core` and all extracted providers.

**Comment by geemus** [comment]
@Temikus thanks for the heads up, we're working on it.

**Comment by plribeiro3000** [comment]
@Temikus We need to remove ruby `1.9.3` as well. Could you take care of that?

**Comment by Temikus** [comment]
@plribeiro3000 Took care of that a while ago, sorry, forgot to update here.
Has the deprecation been completed? Or are we still tracking stuff in this bug?

**Comment by plribeiro3000** [comment]
i guess you are right @Temikus. We might be missing only a new release.

**Comment by icco** [comment]
I released when 1.9.3 got removed.

**Comment by geemus** [comment]
I think I have a plan here to make this more tenable. Basically I hope to change the net-ssh requires to optional (require/rescue+warn). That should remove the dependency altogether for people that don't even need it and let those who do manage their own ssh versions. This would then let 1.9.3 remain workable for a bit longer.

**Comment by milani** [comment]
I use `fog` in my rails app. I used bundler to update the dependencies. Now, the rails app doesn't work with following error: 
```
LoadError: cannot load such file -- net/ssh
my-app/config/application.rb:7:in `<top (required)>'
my-app/Rakefile:4:in `<top (required)>'
```

I could resolve the issue adding `net-ssh` to my `Gemfile`. I think it is the result of: https://github.com/fog/fog-core/commit/7a87027df7666a27ea60a06c8299c4c5c46f478b

**Comment by plribeiro3000** [comment]
@geemus This changes seems to be broken. =s
Since `fog-core` uses `require` this file will always be required and thus `net-ssh` will always be required even when the used does not want to.

thoughts?

**Comment by geemus** [comment]
fog-core shouldn't actually require now, or at least it should fail nicely. fog itself still needs a release though.

**Comment by geemus** [comment]
I think this is (hopefully) temporarily ok again. I've release a new fog to match with fog-core (and it locks to a 1.9 compat version of fog-google). I think I might still need to release a couple of the other related gems, but that we should be good at that point. I guess whether or not we should try to make fog-google come back to 1.9 compat is a broader question. I think for now it can go it's own way, but that we'll need to leave it locked in fog.
