### ISSUE TITLE
Incorrect net/ssh missing error messages

### ISSUE THREAD

**Issue by JustMcAfee** [fog/fog-core#167]
When net-scp is not found, fog-core prompts to install net-ssh.  This is misleading, and occurs even if net-ssh is in fact installed.

**Comment by plribeiro3000** [comment]
Good catch. The wrong message is [here](https://github.com/fog/fog-core/blob/master/lib/fog/core/scp.rb#L46). Can you open a PR with this fix?

**Comment by geemus** [comment]
@plribeiro3000 cool, thanks for catching that.
