### ISSUE TITLE
mime-types update has broken tags

### ISSUE THREAD

**Issue by penfold45** [fog/fog-core#169]
Hi

I think the latest upgrade of mime-types has broken all old versions of fog. I am still very new to ruby and gems but as far as I can tell this line pulls the latest version off mime-types which just got updated to require Ruby 2

    spec.add_dependency("mime-types")

I have tried installing a specific version mime-types before installing fog but it seems still to install the latest mime-types.

Any idea how I can get around this?

Thanks

**Comment by geemus** [comment]
I guess we probably need to pin the dependency inside fog to an earlier version. In theory in your app I think you could also do this in your Gemfile to get it to work ok. We would certainly welcome a patch to lock the version here as well (as we are intending to maintain 1.9 compatibility a bit longer at least, though it seems to be getting harder all the time to do so).

**Comment by rwngallego** [comment]
I have this same issue

**Comment by geemus** [comment]
working toward a fix here: https://github.com/fog/fog-core/pull/170
