### ISSUE TITLE
`mime-types` gem is not added in the gemspec

### ISSUE THREAD

**Issue by NimishaS** [fog/fog-core#177]
`mime-types` gem is required here https://github.com/fog/fog-core/blob/master/lib/fog/storage.rb#L11, but it's not added in the `gemspec` dependencies. 
This is causing Travis failure for the gems which are using `fog`.

**Comment by Temikus** [comment]
@NimishaS `mime-types` was unbundled from `fog` gem to prevent ruby <2.0 compatibility issues, see: https://github.com/fog/fog/issues/3775

For now, I suggest you specify the dependency directly in your `Gemfile`
