### ISSUE TITLE
Bump excon to >=0.49.0

### ISSUE THREAD

**Issue by voelzmo** [fog/fog-core#184]
Hi,

could we please get a fog-core version with excon bumped to >=0.49.0? 

We're seeing freezes exactly as described in https://github.com/excon/excon/issues/542 in [`ssl_socket`](https://github.com/excon/excon/blob/v0.45.4/lib/excon/ssl_socket.rb#L122) and commit https://github.com/excon/excon/commit/192bb842e70b550ed6d78c6d621962ee0faca4be introduces a timeout in that very line.

Apologies upfront: I didn't follow the excon changelog very closely, so I have no idea if anything else changed from 0.45.4 which might prevent such an update.

Thanks!

**Comment by geemus** [comment]
Thankfully, I maintain both, so I'm pretty comfortable in saying a bump shouldn't cause further issues (except maybe in some jruby versions, but that is a whole other can of worms and exists through a number of versions).

**Comment by geemus** [comment]
released in v1.38.0

**Comment by voelzmo** [comment]
Wow, awesome, that was fast. Thanks a million!
