### ISSUE TITLE
Container Service

### ISSUE THREAD

**Issue by seanhandley** [fog/fog-core#188]
I'm looking to add Container support to `fog-openstack` via the Magnum project.

I'm unsure which other cloud technologies provides APIs for container services but given the popularity of containers over the past few years I think it's a worthwhile service type to add.

Thoughts welcome.

**Comment by plribeiro3000** [comment]
Hmm. I guess is something that we could have but dunno how to go from this.
We just created `NFV` just for openstack. I'm afraid that at this rat we will create tons of services just for `openstack` but i do get that is something we might want to have.

cc/ @geemus

**Comment by seanhandley** [comment]
OpenStack's a difficult one because new projects come out all the time and new releases are once every six months.

I don't think it's necessary (or reasonable) for Fog to support all OpenStack sub-projects but I think a container service is probably available or available soon in other cloud providers' APIs.

**Comment by plribeiro3000** [comment]
Isn't another way to do this without pushing stuff to core? Maybe a workaround?
I will happily code something to make that happen.

**Comment by seanhandley** [comment]
There's nothing stopping `fog-openstack` creating its own core classes for containers.

The questions is long term maintainability of all Fog sub projects.

**Comment by plribeiro3000** [comment]
Sure. I agree. I'm just worried that we might explode the number of Services in `core` which is shared with services only used by `openstack`.

I totally understand the reason to push this kind of stuff to core but perhaps we should have a way to do this inside the provider first and once others need it as well we push it to code. 

I believe you might be able to register a Service inside `fog-openstack`, no?

**Comment by geemus** [comment]
Also, if there are other services that already explicitly have container services that helps (even if we don't support them). I certainly think it is likely that things are headed in this direction, but I haven't seen much of it concretely yet.
