### ISSUE TITLE
Bump up fog-core to fix failing tests

### ISSUE THREAD

**Issue by Temikus** [fog/fog-core#193]
Can we release a new version with #192 and bump up the gemspec in `fog/fog` so the tests stop failing?

/CC @geemus @plribeiro3000

**Comment by plribeiro3000** [comment]
@Temikus Is up to @geemus here. I don't have access to release this.

**Comment by geemus** [comment]
Thanks for the ping, I'm on it.

**Comment by geemus** [comment]
released in 1.40.1, will follow up with fog release shortly

**Comment by geemus** [comment]
gemspec is bumped, guess release shouldn't be strictly necessary, though we might be due for one

**Comment by vemv** [comment]
Care to explain this issue and its status? I can't quite follow.

What I know is that my CI builds are failing. I see 1.40.1 in rubygems (and it's installed in my machine) though, so I'm not really sure if it's Fog or Codeship the one at fault.

![image](https://cloud.githubusercontent.com/assets/1162994/16463031/4b18b212-3e34-11e6-8214-c95befa67033.png)

**Comment by geemus** [comment]
I think I had specified the dependency incorrectly in the gemspec for fog, and I had thought it was now fixed. 1.40.1 should be available as can be seen here: https://rubygems.org/gems/fog-core. Are you using the latest master?

**Comment by vemv** [comment]
> Are you using the latest master?

fog was an indirect dependency (i.e. not declared in my Gemfile). re-generating Gemfile.lock from scratch didn't fix the issue.

As a temporary workaround I added `gem 'fog-core', '1.38.0'` to my Gemfile, that made Codeship happy.

**Comment by geemus** [comment]
Strange, I think a `bundle update` or something would hopefully do it (that seemed to work directly in the `fog/fog` case).

**Comment by Temikus** [comment]
Cannot reproduce it on my setup:
```
λ bundle
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
...
Installing fog-core 1.40.1 (was 1.40.0)
...
```
There may be some issues on the Codeship side or in how your project gems are specified. 
I'll need a more detailed repro to understand the situation.

**Comment by geemus** [comment]
Maybe some out of date caches or something? Hopefully it will all clear up soonish.

**Comment by arteezy** [comment]
It's not Codeship specific, I get the same error on Travis CI:
```
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Could not find fog-core-1.40.1 in any of the sources
```
I can install this gem manually on all my machines (locals and remotes), but on CI it fails. 

Two days have passed since release, so I doubt it's cache

**Comment by vemv** [comment]
> Cannot reproduce it on my setup

I couldn't reproduce the issue in my laptop either, only CI. Just like @arteezy experiences.

> Maybe some out of date caches or something? Hopefully it will all clear up soonish.

Codeship has a 'clean dependency cache' option, but it didn't work.

Given that the CI issue is somewhat confirmed, I suggest a dummy version bump. Seems like `1.40.1` was an erratic release - maybe there was some kind of strange interaction (like race conditions) between rubygems and CI providers.

**Comment by arteezy** [comment]
1.41.0 is working. Thanks for resolving this issue quickly.

**Comment by geemus** [comment]
Certainly, thanks for your patience and understanding in the mean time.
