### ISSUE TITLE
Time to get a new service: How to restructure?

### ISSUE THREAD

**Issue by gildub** [fog/fog-core#199]
There is a structural issue with the current Service class.
Namely, each subclass Service has a `service` method which creates a circular reference for each service within itself. 
This is defined dynamically in [1], the meta programming is not the issue here, but this is effectively unfortunate and has several impacts including making it hard to troubleshoot services defined in fog sub-projects.

A good way, I've found so far, to address this loop issue is to have the requests for a service (list_user, list_subnets, create_*, etc) defined as modules and mixed-in into the Service class.

But besides the impact of changing the service, I believe it's an opportunity to step back at bit and look how Service could evolve.

In summary, a given cloud has:
- a main URL endpoint
- required credentials 
- eventually some options
- and many services which share the above.

So creating a session to a cloud basically means initiate a connection and share that information to be used for API transactions to each service.

Let's see what it would be ideal to be able to consume:

``` ruby
my_cloud = Fog::Openstack::Cloud.new(url, credentials)
```

The my_cloud object (holds authentication details, catalog information, etc) is done only once and used by any service one might need:

``` ruby
@connection = Fog::Openstack::Service2::Network.new(my_cloud, options)
```

The requests can be used as usual:

``` ruby
subnets = @connection.list_subnets
```

Also we could ultimately offer the user a better experience to have the services automatically available. The Cloud class to dynamically attach services using composition:

``` ruby
my_cloud = Fog::Openstack::Cloud.new(url, credentials)
subnets = my_cloud.network.list_subnets
```

In summary, it would be lovely to have:
- A base Cloud class holding:
  - main URL endpoint
  - authentication details
  - service endpoints (catalog) 
  - global options (including service specific options if needed: `{ network => {...}, ... }`)
- A Service class
  - A different interface accepting a cloud object
  - No service method but instead the Requests are defined as modules and mixed in
- Ultimately, augment the Cloud class to offer the services automatically. 

Besides being part of a new major release, the new Service class could be introduced as a Service2 and then announce a deprecation for the current Service class.

Any thoughts?

[1] https://github.com/fog/fog-core/blob/master/lib/fog/core/service.rb#L32-L52

**Comment by geemus** [comment]
Hey, thanks for your feedback. I don't think I quite follow what you are going for. Are you seeing particular issues around the current service interface that you could detail? It sounds like the main distinction you describe here is that you could have creds setup once to interact with any of the individual services that make up a particular providers' offerings?

**Comment by gildub** [comment]
@geemus,

The issue I'm seeing is not specific but structural, as you commented in line #52 (aforementioned source snippet). 

And at the same time, while restructuring the service, then having a Cloud object will effectively allow to do setup (creds, main endpoint and global config) only once but it will also allow to have all services directly available (still autoloaded though) under that same Cloud object.

**Comment by geemus** [comment]
I'm afraid I'm still not really getting the what benefit we would see for doing this work yet, at least if there isn't a particular issue it addresses. Not sure yet what I'm missing.

**Comment by gildub** [comment]
This is not issue driven, it's a design question. Especially in the perspective of new major release coming as @plribeiro3000 mentioned in #198.

**Comment by geemus** [comment]
Got it, thanks for clarifying. I'm not yet sure I totally grok what the change would look like to support this, but am open to discussing in more depth. The challenge with a change like this seems like it would come in trying to maintain backwards compatibility and also ensuring all the existing services were ported in a timely fashion.

**Comment by gildub** [comment]
Well I suppose if this is done as part of a new major release it would be understandable if it's not backward compatible.

**Comment by gildub** [comment]
Would it be possible to get a Version 2 branch created?

@geemus

**Comment by geemus** [comment]
Yes, though I'm cautious to do so too early (lest it linger). I think a focus toward continuing to split things out for 2.0 is more than enough work at this point, without a refactor in addition. But I do want the code quality to improve over time.

**Comment by gildub** [comment]
So what's the timeframe?

**Comment by geemus** [comment]
Great question. It may depend on buy-in. It would be hard, for instance, for you and I to do all of the necessary work to get this done. If we had some broader push that might be better. From my perspective, splitting out the various sub-libraries would also be the bigger win of things for the near term (and therefore what I would be most likely to push on in terms of progress). Does that make sense?

**Comment by gildub** [comment]
Sorry I'm not following you. Without a new branch, nothing can happen.

**Comment by gildub** [comment]
Sorry I'm not following you. Without a new branch, nothing can happen.

**Comment by geemus** [comment]
Fair enough, sorry we seem to be talking around one-another. I think it may be easiest if you wanted to just work in a branch on a fork initially? That way you can have more complete control, instead of being blocked on me changing things for you.

**Comment by gildub** [comment]
Sure. Thanks
