### ISSUE TITLE
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

### ISSUE THREAD

**Issue by svergeylen** [fog/fog-core#202]

**Comment by plribeiro3000** [comment]
@svergeylen Fog does not have any native extensions itself.
Could you please provide the logs so i can take a look and figure out which dependency is causing this?

Thanks!

**Comment by geemus** [comment]
Might be fog-xml (which uses nokogiri), otherwise I'm not aware of any likely culprits. Anyway, looks like there is a lack of detail here to proceed, so going to close, but feel free to comment/reopen.

**Comment by svergeylen** [comment]
I deleted the content due to the fact it was not a fog-core issue, but was unable to delete it entirely ;-)

**Comment by geemus** [comment]
@svergeylen got it, thanks for clarifying.
