### ISSUE TITLE
mime/types gem needed in the core

### ISSUE THREAD

**Issue by gildub** [fog/fog-core#203]
This is not a new issue [1],

meanwhile it definitely seems to make sense to have fog-core to tackle it and include the gem as discussed in [2].

[1] https://github.com/fog/fog-core/issues/177
[2] https://github.com/fog/fog-openstack/pull/196

**Comment by icco** [comment]
As stated in #177, until Fog removes 1.9.3 as a supported ruby, we cannot.

 > mime-types was unbundled from fog gem to prevent ruby <2.0 compatibility issues, see: fog/fog#3775

The fog issue to follow for removing 1.9.3 support is fog/fog#3872

I'll leave this open as it is something we want to eventually do once fog 2.0 is released.

**Comment by gildub** [comment]
@icco 

Understand, we've to keep it that way until Ruby 1.9.3 is removed.
Hopefully this is about to happen soon enough.

**Comment by syguer** [comment]
It has begun https://github.com/fog/fog/pull/3974

**Comment by plribeiro3000** [comment]
@gildub Do you have some spare time to send a PR adding it?

Thanks!

**Comment by gildub** [comment]
@plribeiro3000, a PR to do what? Sorry but I'm losing track here, PR#221 has addressed the missing dependency isn't ?

**Comment by plribeiro3000** [comment]
Yeap. Not sure what I was thinking. Heheh

Thanks @gildub!
