### ISSUE TITLE
Fix Travis for < 2.0

### ISSUE THREAD

**Issue by icco** [fog/fog-core#205]
As discovered in #204, travis is broken for ruby < 2.0, also we still haven't dropped <2.1 support until https://github.com/fog/fog/issues/3872 is closed.

**Comment by plribeiro3000** [comment]
This is not needed because we do not support `ruby < 2.0` anymore.

The build does not include it either:

https://github.com/fog/fog-core/blob/master/.travis.yml#L3-L9

**Comment by geemus** [comment]
Thanks!
