### ISSUE TITLE
1.44.0 depends on xmlrpc

### ISSUE THREAD

**Issue by BanzaiMan** [fog/fog-core#206]
https://github.com/fog/fog-core/blob/v1.44.0/fog-core.gemspec#L24

And it's breaking on Ruby < 2.3.

```sh-session
travis@1245b61e9931:~$ ruby --version
ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]
travis@1245b61e9931:~$ gem --version
2.6.11
travis@1245b61e9931:~$ gem install fog-core
Fetching: builder-3.2.3.gem (100%)
Successfully installed builder-3.2.3
Fetching: excon-0.55.0.gem (100%)
Successfully installed excon-0.55.0
Fetching: formatador-0.2.5.gem (100%)
Successfully installed formatador-0.2.5
ERROR:  Error installing fog-core:
        xmlrpc requires Ruby version >= 2.3.
```

```sh-session
travis@1245b61e9931:~$ ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
travis@1245b61e9931:~$ gem --version
2.6.11
travis@1245b61e9931:~$ gem install fog-core
Fetching: builder-3.2.3.gem (100%)
Successfully installed builder-3.2.3
Fetching: excon-0.55.0.gem (100%)
Successfully installed excon-0.55.0
Fetching: formatador-0.2.5.gem (100%)
Successfully installed formatador-0.2.5
Fetching: xmlrpc-0.3.0.gem (100%)
ERROR:  Error installing fog-core:
        xmlrpc requires Ruby version >= 2.3.
```

**Comment by geemus** [comment]
@icco @plribeiro3000 @shaiguitar I believe we added this to try and fix travis? Any ideas on what we should adjust?

**Comment by shaiguitar** [comment]
Hmm, the gemspec clearly isn't working well:
```
  spec.add_dependency("xmlrpc") if RUBY_VERSION.to_s >= "2.4"
```

Let me try out an older version of ruby and install from local dir gemspec.

**Comment by shaiguitar** [comment]
This does work locally for me:

```
shai@lappy ~/r/fog-core [master] ± % ruby -v
ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-darwin14]

shai@lappy ~/r/fog-core [master] ± % gem -v
2.4.5.1
# built with gem build *gemspec
shai@lappy ~/r/fog-core [master] ± % gem install fog-core-1.44.0.gem
Fetching: builder-3.2.3.gem (100%)
Successfully installed builder-3.2.3
Fetching: excon-0.55.0.gem (100%)
Successfully installed excon-0.55.0
Fetching: formatador-0.2.5.gem (100%)
Successfully installed formatador-0.2.5
Successfully installed fog-core-1.44.0
Parsing documentation for builder-3.2.3
Installing ri documentation for builder-3.2.3
Parsing documentation for excon-0.55.0
Installing ri documentation for excon-0.55.0
Parsing documentation for formatador-0.2.5
Installing ri documentation for formatador-0.2.5
Parsing documentation for fog-core-1.44.0
Installing ri documentation for fog-core-1.44.0
Done installing documentation for builder, excon, formatador, fog-core after 2 seconds
4 gems installed
```

**Comment by BanzaiMan** [comment]
It fails for 2.2.5 as well for me.

```sh-session
travis@1245b61e9931:~$ rvm install 2.2.5
Searching for binary rubies, this might take some time.
Found remote file https://rubies.travis-ci.org/ubuntu/12.04/x86_64/ruby-2.2.5.tar.bz2
⋮
travis@1245b61e9931:~$ ruby -v
ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-linux]
travis@1245b61e9931:~$ gem update --system
Updating rubygems-update
Fetching: rubygems-update-2.6.11.gem (100%)
Successfully installed rubygems-update-2.6.11
Installing RubyGems 2.6.11
RubyGems 2.6.11 installed
⋮
RubyGems installed the following executables:
        /home/travis/.rvm/rubies/ruby-2.2.5/bin/gem

RubyGems system software updated
travis@1245b61e9931:~$ gem install fog-core
Fetching: builder-3.2.3.gem (100%)
Successfully installed builder-3.2.3
Fetching: excon-0.55.0.gem (100%)
Successfully installed excon-0.55.0
Fetching: formatador-0.2.5.gem (100%)
Successfully installed formatador-0.2.5
Fetching: xmlrpc-0.3.0.gem (100%)
ERROR:  Error installing fog-core:
        xmlrpc requires Ruby version >= 2.3.
```

Could you try installing it from rubygems.org?

**Comment by BanzaiMan** [comment]
How did you get `fog-core-1.44.0.gem`?

```sh-session
travis@1245b61e9931:~$ gem fetch fog-core
Fetching: fog-core-1.44.0.gem (100%)
Downloaded fog-core-1.44.0
travis@1245b61e9931:~$ gem install fog-core-1.44.0.gem
ERROR:  Error installing fog-core-1.44.0.gem:
        xmlrpc requires Ruby version >= 2.3.
```

**Comment by shaiguitar** [comment]
What is the status of ruby versions and fog version support? It seems like there are compatibility matchups for the various versions. @icco mentioned #205 when #204 was released. It seems like travis has been broken for some time with respect to different ruby versions. The xmlrpc dep was removed from 2.4 as per https://bugs.ruby-lang.org/issues/12160 so it is necessary for ruby versions 2.4 and above.

**Comment by BanzaiMan** [comment]
`if RUBY_VERSION >= "2.4"` is respected at the time the gem is built. This is not evaluated at the install time. I suspect the gem uploaded was built with a Ruby that satisfies this requirement, thus adding the dependency.

**Comment by BanzaiMan** [comment]
It is fine to add this `xmlrpc` dependency. I understand the reasoning. But it is appreciated if you could recognize this in `fog-core`'s gemspec as well.

**Comment by shaiguitar** [comment]
Is there a correct way to build/upload to rubygems so this gets evaluated correctly? That line for xmlrpc was added in mimicking the other specific ruby dep constraints. 

We can remove the xmlrpc dependency in gemspec right now in order to resolve these problems if there is no other way (better 2.4 not working than all previous versions) but ideally we can make the rubygem version upload work? @geemus ?

**Comment by majormoses** [comment]
@shaiguitar  http://www.programmersparadox.com/2012/05/21/gemspec-loading-dependent-gems-based-on-the-users-system feels like it should work for us though is kinda a hacky.

**Comment by xbeta** [comment]
Can this be merge immediately? We are having the same issue.

**Comment by shaiguitar** [comment]
The gemspec ruby version conditionals in there should be revisited in general. But if I could right now I would merge #207 (remove this dep) and release but do not have the rights.

**Comment by majormoses** [comment]
@geemus any chance we can get this hotfixed and then implemented properly as outlined in https://github.com/fog/fog-core/issues/206#issuecomment-298175467?

**Comment by Temikus** [comment]
CC/ @tokengeek @krames who also have the rights to push to fog-core. I, sadly, don't have access to push core to RubyGems.

**Comment by geemus** [comment]
On it, sorry for delays, I hadn't seen how severe this was.

**Comment by geemus** [comment]
I removed the dependency and released again. Not sure how much it's worth trying to do the hacky workaround or not (as we want to reduce/remove support for old stuff anyway). Maybe we should just accept and set some of those travis to allowed fails (or remove them). We had hoped to make it last until we could finish separation and do fog 2.0, but we could of course do 2.0 to drop old support and 3.0 to finish the separation...
