### ISSUE TITLE
Conditionally install `xmlrpc` on ruby versions >= 2.4

### ISSUE THREAD

**Issue by majormoses** [fog/fog-core#212]
## Background:
- https://bugs.ruby-lang.org/issues/12160
- https://github.com/ruby/xmlrpc

Basically `xmlrpc` was removed from stdlib due to lack of maintainer responsiveness. Unfortunately due to the way ruby + rubygems works this is not as simple a problem as we saw caused here: #206 . 

## The solution
There is one way of working around this that I am ware of, by using a ruby extension. In another project where I am a maintainer I proposed to solve this via  https://github.com/sensu-plugins/sensu-plugins-supervisor/pull/22 if you would like me to whip up a similar PR I am more than happy to do so. The only drawbacks to this approach:
-  is the need of a c compiler which I have not checked if you already have this dependency.
- it not being obvious to users that this is the case and may be confusing to those not familiar with building ruby/c extensions

**Comment by geemus** [comment]
Thanks for the detailed report. The only usage I'm seeing in fog-core is in a test (and I didn't see any usage in fog/fog either). So, I think to simplify for this context I'm just going to drop that one test. I don't see it in the major providers and don't recall where it was introduced from exactly. I'll keep this in mind should that not work out and/or if I figure out which provider actually needs it. Thanks!
