### ISSUE TITLE
Log all requests to a specific IO location (i.e a file)

### ISSUE THREAD

**Issue by seanhandley** [fog/fog-core#215]
I have a Rails app that makes extensive use of fog-openstack. Is there a way via fog-core or excon to configure debug output to save directly to a file?

Ideally I want to pipe the Excon request debug output into a piece of code that can extract meaningful data from it and log to a separate file.

Any thoughts/advice appreciated!

**Comment by icco** [comment]
Yeah, in your configuration, you can use https://github.com/fog/fog-core/blob/f6ef6c3d9458bc235be57100acdced264e85e52a/lib/fog/core/logger.rb#L14 to override.

Something like this:

```
Fog::Logger.channels[:debug] = 'logfile.log'
```

**Comment by seanhandley** [comment]
Thanks @icco - I couldn't get that to work. But the Excon instrumentor stuff is working fine now 👍 

https://github.com/excon/excon#instrumentation

**Comment by geemus** [comment]
Great, glad to hear you found a way to make it work for you.
