### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by bilal-naeem-confiz** [fog/fog-core#222]
Hi,
I am working on `fog-azure-rm` and have been running into a `mime-types` dependency issue which has now been fixed in `fog-core`.
I wanted to ask when will a new version of `fog-core` be released so that we can include it in our gemspec and remove the current dependency that we have added for `mime-types`.
Thanks

**Comment by geemus** [comment]
Sorry for the delay (was traveling around holidays). I've now released as 2.0.0 (as dropping 1.9 is potentially breaking). Just let me know if you need anything else, thanks!

**Comment by bilal-naeem-confiz** [comment]
Thanks @geemus

**Comment by aheumaier** [comment]
@geemus  Seems this topic has to be re-discussed
https://github.com/fog/fog-azure-rm/issues/390

**Comment by geemus** [comment]
@aheumaier thanks for the heads up.
