### ISSUE TITLE
Fix :paranoid deprecation in net-ssh

### ISSUE THREAD

**Issue by elconas** [fog/fog-core#226]
When using :paranoid with net-ssh 4.2.0 the following deprecation warning is printed, which is annoing.

```
:paranoid is deprecated, please use :verify_host_key. Supported values are exactly the same, only the name of the option has changed.
```

**Comment by elconas** [comment]
Fixed by https://github.com/fog/fog-core/pull/227

**Comment by plribeiro3000** [comment]
I believe the reason we support both is for users that are still using an old version of `net-ssh`.

If we are going this route, we need to bump our dependency to be `> 4.0` which might be a problem for other users. Maybe we can check the version of `net-ssh` and use the right key?

**Comment by elconas** [comment]
But the fix should be backward compatible. I checked with the net.-ssh repo and the Constant I am accessing is there since 11 years. Right now the gem has no dependency to net-ssh at all I guess ?

**Comment by geemus** [comment]
It looks like we passed `:verify_host_key` all along, so this is just no longer also passing `:paranoid`. Looks reasonable to me, thanks!

**Comment by plribeiro3000** [comment]
👍
