### ISSUE TITLE
Deprecation check breaks code and does not catch deprecation

### ISSUE THREAD

**Issue by tokengeek** [fog/fog-core#242]
With the release of v2.1.1 we've started to see things break in our clients.

I've fixed the immediate issues but there are a few things to consider.

In https://github.com/fog/fog-core/pull/229 the behaviour of `Fog::Core::Provider#service` was changed to output a deprecation warning when the `Fog::<Service>::<Provider>` namespace was used.

However, the `#service_klass` method uses `eval` and catches `NameError` to do this and that changes the behaviour.

In `fog-brightbox` we still have the deprecated layout as well as `autoload` being used. 

Up to v2.1.1 fog's `#service` could be declared first because it did have the same side effects.

From v2.1.1 if the preferred namespace is not available it now outputs the warning then switches to the deprecated naming. When combined with `autoload` the ordering becomes critical. That means `#service` MUST run after autoloading is declared because `eval` (or even `defined?`) can not find the class.

I've had to fix that in https://github.com/fog/fog-brightbox/releases/tag/v0.16.1 but then I noticed another issue.

When autoloading was added years ago (https://github.com/fog/fog-brightbox/commit/37a840877b2a0ae3af4454f97b8a6bceaf8447c1) it was declared such that both `Fog::Compute::Brightbox` and `Fog::Brightbox::Compute` will be resolved!

So with the ordering problem, the deprecation code broke outright. With the autoloading change, now despite using a deprecated namespace there are no deprecation warnings.

I'm not sure how specific these are to `fog-brightbox` but I don't think the deprecation changes are doing what they are supposed to.

```ruby
[I] paul@nixos ~/c/fog-brightbox (master) [I]> git co v0.16.0
HEAD is now at a67efa1 Release v0.16.0
[I] paul@nixos ~/c/fog-brightbox ((v0.16.0)) [I]> bundle exec pry -r "fog/brightbox"
[fog][DEPRECATION] Unable to load Fog::Brightbox::Compute
[fog][DEPRECATION] The format Fog::Compute::Brightbox is deprecated
[fog][DEPRECATION] Unable to load Fog::Brightbox::Storage
[fog][DEPRECATION] The format Fog::Storage::Brightbox is deprecated
[1] pry(main)> Fog::Brightbox::Compute
=> Fog::Brightbox::Compute
[2] pry(main)> Fog::Compute::Brightbox
=> Fog::Compute::Brightbox
[3] pry(main)> exit
[I] paul@nixos ~/c/fog-brightbox ((v0.16.0)) [I]> git co v0.16.1
Previous HEAD position was a67efa1 Release v0.16.0
HEAD is now at 3458411 Release v0.16.1
[I] paul@nixos ~/c/fog-brightbox ((v0.16.1)) [I]> bundle exec pry -r "fog/brightbox"
[1] pry(main)> Fog::Brightbox::Compute
=> Fog::Brightbox::Compute
[2] pry(main)> Fog::Compute::Brightbox
=> Fog::Compute::Brightbox
```

If we output a warning because `Fog::Compute::<Provider>` was declared, that warns people. We shouldn't rely on `eval` and its side-effects.

**Comment by tokengeek** [comment]
I have been working on a v1.0 release of `fog-brightbox` which fixes the namespace issue since it is potentially a breaking change but these issues may already be affecting other providers/users so I think it is something to address in core.

**Comment by geemus** [comment]
Thanks for the heads up and detailed explanation. @plribeiro3000 worked on this, so can probably give the most context to discuss and move this forward. Thanks!

**Comment by tokengeek** [comment]
It looks like there may still be an ordering issue. I've just noticed https://github.com/fog/fog-brightbox/blob/master/lib/fog/brightbox.rb#L35-L36 are happening before the legacy namespaces.

In fog-aws they were listed first, followed by `Fog::AWS` and the autoloads _then_ the `service` calls.

In which case I may be able to fix our issues but it means each provider may need checking.

I'll try to confirm if that changes anything tomorrow.

**Comment by plribeiro3000** [comment]
Ouch. I get it. The problem is that it was defined in both ways because of other modules from within.

I guess we should define those modules from within another file and just define the main modules inside the main file?

**Comment by plribeiro3000** [comment]
No, The main issue is that there is both namespaces defined. All of the models and requests are inside `Fog::Compute::Brightbox` but some config files are defined insice `Fog::Brightbox::Compute`.

**Comment by plribeiro3000** [comment]
I believe you next release `1.0.0` might fix the issue.

Looking back at [release 0.7.2](https://github.com/fog/fog-brightbox/commit/386cd70e67827cf7157eedf42e7520af08ec4a54) there were both namespaces defined and it went carried away.

`Fog::Compute::Brightbox` was defined [here](https://github.com/fog/fog-brightbox/blob/386cd70e67827cf7157eedf42e7520af08ec4a54/lib/fog/brightbox/compute.rb) and
`Fog::Brightbox::Compute` was defined [here](https://github.com/fog/fog-brightbox/blob/386cd70e67827cf7157eedf42e7520af08ec4a54/lib/fog/brightbox/compute/config.rb)

This explains why we did not have this issue in `fog-aws`.

Maybe we should check for this behaviour as well in `fog-core`?

**Comment by tokengeek** [comment]
Yes. I mentioned that in the original report. By having both schemes we are suppressing the deprecation warning whilst we are transitioning in `1.0.0`

If we want to report the deprecation `Fog::Compute::Brightbox` is being used, then the check done by `#service` needs to happen at the correct time, which would be after things are defined.

But I think we should be warning if it is defined rather than trying any tricks with `eval` and variations.

I'll have a look tomorrow to see what is viable. At the very least if similar issues arise, we have a core ticket to point people at.

**Comment by plribeiro3000** [comment]
Gotcha @tokengeek . Thanks for the explanation.

**Comment by plribeiro3000** [comment]
@kddeisz Yeap. Switch all your definitions to be under `Fog::Local`. Thats the preferable method from now on.

`Fog::Compute`, `Fog::Storage`, `Fog::XXXXXX` are all deprecated in favor of `Fog::Provider::Compute`, `Fog::Provider::Storage`, `Fog::Provider::XXXXXX`.
