### ISSUE TITLE
Print error message when loading provider

### ISSUE THREAD

**Issue by Paxa** [fog/fog-core#248]
If provider have some error `LoadError` or `NameError` then it just print `XXX has no YYY service`.
But provider can be found but there is error while loading it, e.g. missing some other dependency or dependency's code changed

Also hard to develop a provider...

We can change error message here
https://github.com/fog/fog-core/blob/adffc543c71e5db7aefaf70e2520c9a7bc968cb7/lib/fog/core/services_mixin.rb#L30
to something like this:
```ruby
    rescue LoadError, NameError => err # Only rescue errors in finding the libraries, allow connection errors through to the caller
      err_msg = err.message.sub(/Did you mean\?.+$/, '').strip
      raise Fog::Service::NotFound, "#{provider} has no #{service_name.downcase} service (#{err_msg} - #{err.backtrace.first})"
    end
```

**Comment by geemus** [comment]
Thanks for the detailed report, I'm certainly open to improving messages. Something like your proposal sounds like a good first pass at this. Would you be willing to work it into a pull request for us? Thanks!
