### ISSUE TITLE
verify_host_key: false is deprecated, use :never

### ISSUE THREAD

**Issue by militarpancho** [fog/fog-core#251]
Hi, I see this error always I use Fog::SSH...maybe it could be convenient to change the code of ssh.rb to use the :never mentioned in the warning, don't it?

**Comment by geemus** [comment]
Hey, thanks for the heads up. Yeah, I think that makes sense to update. Looking at the code, it appears that we already had to make a similar change when the option prior to verify_host_key also changed (and it has some code in place to be cautious about changing the options for people who might be using old versions of net-ssh). Would you be open to working on a patch? I'm not actively doing anything with fog ssh at present, so it might be safer that way so you can make sure it works as expected. Thanks!
