### ISSUE TITLE
Showing Source Location Depreciation Warnings 

### ISSUE THREAD

**Issue by sshaw** [fog/fog-core#252]
Hi, after upgrading to the new Fog paradigm I'm getting a ton of warnings:

> [fog][DEPRECATION] Unable to load Fog::Rackspace::CDN
> [fog][DEPRECATION] Falling back to deprecated constant Fog::CDN::Rackspace. The preferred format of service provider constants has changed from service::provider to provider::service. Please update this service provider to use the preferred format.

The problem I'm having is identifying _where_ these warnings are coming from. 

After some cursory silver searching, it appears that they're coming from some gems. 

Given some of the common Fog use cases, e.g., via Paperclip, CarrierWave, etc.., where one never uses `Fog::Rackspace::CDN` but rather something like `x.credentials[:provider] = 'Rackspace'`, finding the source can be difficult; a stacktrace –or some indicator of source location– would be helpful.

**Comment by geemus** [comment]
Sure, that makes sense. Would you be interested in helping with a patch to provide some more context? Thanks!
