### ISSUE TITLE
IRC channel

### ISSUE THREAD

**Issue by lzap** [fog/fog-core#266]
Hey,

the advertised IRC channel is quite empty, specifically, there's only `sbryant` there. I also checked libera, but after the freenode clusterfuck I wonder if the community moved somewhere else. The fog.io site still advertise freenode.

Cheers

**Comment by geemus** [comment]
Good questions. The activity dropped off quite some time ago, and the freenode stuff doesn't help. I'm fine removing those references/advertisements to better reflect reality. It doesn't seem like there has been a need for something of this ilk in a while, and we can add something back if/when needed. Does that make sense for you?

**Comment by lzap** [comment]
That is fine, I think github is allright. Issues can be used for discussions like this one. Cheers.

**Comment by geemus** [comment]
I removed/updated references here: https://github.com/fog/fog.github.com/commit/682c4f8a8732cc0cd4122990b221e7470e97f95f

Feel free to offer PRs on the website also if you see issues (and/or file issues directly on the repo).
