### ISSUE TITLE
SFTP support

### ISSUE THREAD

**Issue by pablomh** [fog/fog-core#270]
I'd like to request support for SFTP similar to the one provided fot SCP protocol.

**Comment by plribeiro3000** [comment]
@pablomh We have a list of providers to add next. You can see them here: fog/fog#3644

Since we have FTP, FTPS and SFTP i believe it would be a better fit to have it as a new provider but i can easily see it as a new service here.

@geemus WDYT?

**Comment by pablomh** [comment]
I may try to port it based on the SCP one, but it'll be my first ruby code, so I don't promise anything :)

**Comment by plribeiro3000** [comment]
@pablomh Cool! Let me know if i can help with something.

**Comment by geemus** [comment]
Hey, yes I think setting it up as a distinct provider sounds like a good plan. If you have time and interest to work on it that would be great. Definitely happy to answer questions and review things as you progress.
