### ISSUE TITLE
Consider switching from coveralls to coveralls_reborn

### ISSUE THREAD

**Issue by micwoj92** [fog/fog-core#290]
https://github.com/fog/fog-core/blob/75b972e0d241a4e40911c1003643605533dba26b/fog-core.gemspec#L31C7

More info in this comment from coveralls-ruby repo: https://github.com/lemurheavy/coveralls-ruby/pull/172#issuecomment-1476869465

coveralls-ruby is used in multiple repos in this org, should I open separate issues for every instance if desired?
https://github.com/search?q=org%3Afog+coveralls+path%3A*.gemspec&type=code

**Comment by geemus** [comment]
@micwoj92 Switching sounds fine to me. Issues are probably fine, though a PR would be even better if you have bandwidth. Thanks.

**Comment by geemus** [comment]
@micwoj92 sounds good, just let us know if you won't be able to get to it for whatever reason. Thanks!

**Comment by micwoj92** [comment]
Is coveralls even used anymore for fog?
There was a commit to remove it https://github.com/fog/fog-core/commit/ac3f1d12fe9382af109f67384a48b5668cd2fe78
The last build for fog related repos on coveralls site was couple years ago https://coveralls.io/github/fog
