### ISSUE TITLE
Fog::Collection delegates methods to Array, which doesn't work for methods with keywords in Ruby 3.2

### ISSUE THREAD

**Issue by DimitriosLisenko** [fog/fog-core#293]
# Context
Ruby 3.2 makes it so that delegating `*args` to a method that accepts keywords an ArgumentError. This is what's happening in Fog::Collection because it delegates methods to Array with *args, but some Array methods accept keywords (e.g. `Array#shuffle`).

# Solution
For maximum compatibility across all Ruby 2.x and 3.x versions, methods that delegate with `*args` should be marked with `ruby2_keywords`. I have created a PR here to address this: https://github.com/fog/fog-core/pull/292

# Relevant links
https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/
https://eregon.me/blog/2019/11/10/the-delegation-challenge-of-ruby27.html

**Comment by geemus** [comment]
I believe this was closed by #296
