### ISSUE TITLE
Add #recognizes, #requires, #readonly to model

### ISSUE THREAD

**Issue by plribeiro3000** [fog/fog-core#92]
> For automatic discovery it would be helpful if Service-attributes could be exposed as required (read/write), optional (read/write) and read-only. Currently the services only expose a list of all attributes (Fog::AWS::Server.attributes) without the type of the individual attributes.
> 
> E.g. it would be nice if we had something like Fog::AWS::Server.recognizes, Fog::AWS::Server.requires, Fog::AWS::Server.readonly - akin to Fog::AWS.requires and Fog::AWS.recognizes.
> 
> (or, if there's already a way to determine the attribute-types through reflection, I'd appreciate a pointer)

Original issue by @m-o-e at fog/fog#1675

**Comment by geemus** [comment]
Would be happy to support this work, but probably don't have time to do it myself. Given the lack of activity, it also doesn't seem like there is particularly high demand at this time.
